## 1 Importando bibliotecas e obtendo dataset

### 1.1 Importando bibliotecas

In [1]:
import os
import zipfile
import pandas as pd
import duckdb

### 1.2 Download e leitura do dataset

* Definindo as variáveis para download
* Fazendo download do dataset
* Carregando o dataset sem extração manual de arquivos

In [2]:
# Definindo variáveis

dataset_folder = 'datasets'
dataset_owner = 'asaniczka'
dataset_name = 'top-spotify-songs-in-73-countries-daily-updated'
dataset_download_command = f"{dataset_owner}/{dataset_name}"
dataset_type = '.zip'
dataset_path = os.path.join(dataset_folder, dataset_name + dataset_type)

In [3]:
# Fazendo o download do dataset

if not os.path.exists(dataset_folder):
    os.makedirs(dataset_folder)

if os.path.exists(dataset_path):
    os.remove(dataset_path)

!kaggle datasets download -d {dataset_download_command} -p {dataset_folder}

if os.path.exists(dataset_path):
    print(f"success: {dataset_path}")
else:
    print("error")

Dataset URL: https://www.kaggle.com/datasets/asaniczka/top-spotify-songs-in-73-countries-daily-updated
License(s): ODC Attribution License (ODC-By)
Downloading top-spotify-songs-in-73-countries-daily-updated.zip to datasets

success: datasets\top-spotify-songs-in-73-countries-daily-updated.zip

  0%|          | 0.00/113M [00:00<?, ?B/s]
  1%|          | 1.00M/113M [00:00<01:31, 1.28MB/s]
  2%|▏         | 2.00M/113M [00:00<00:44, 2.59MB/s]
  4%|▎         | 4.00M/113M [00:01<00:20, 5.51MB/s]
  6%|▌         | 7.00M/113M [00:01<00:11, 9.93MB/s]
  9%|▉         | 10.0M/113M [00:01<00:07, 13.6MB/s]
 12%|█▏        | 14.0M/113M [00:01<00:05, 18.9MB/s]
 15%|█▌        | 17.0M/113M [00:01<00:04, 20.9MB/s]
 19%|█▊        | 21.0M/113M [00:01<00:03, 25.3MB/s]
 21%|██▏       | 24.0M/113M [00:01<00:03, 26.5MB/s]
 24%|██▍       | 27.0M/113M [00:01<00:03, 25.5MB/s]
 28%|██▊       | 32.0M/113M [00:02<00:02, 30.8MB/s]
 32%|███▏      | 36.0M/113M [00:02<00:02, 30.3MB/s]
 35%|███▌      | 40.0M/113M [00:02<00:02, 29.6MB/s]
 38%|███▊      | 43.0M/113M [00:02<00:02, 29.6MB/s]
 42%|████▏     | 47.0M/113M [00:02<00:02, 32.1MB/s]
 45%|████▌     | 51.0M/113M [00:02<00:02, 32.1MB/s]
 49%|████▊     | 55.0M/113M [00:02<00:02, 29.4MB/s]
 52%|█████▏    | 59.0M/113M [00:02<00:01, 31.8MB/s]
 56%|█████▌    | 63.0M/113M [00:03<00:01, 32.9MB/s]
 59%|█████▉    | 67.0M/113M [00:03<00:01, 32.4MB/s]
 63%|██████▎   | 71.0M/113M [00:03<00:01, 28.4MB/s]
 66%|██████▌   | 74.0M/113M [00:03<00:01, 26.2MB/s]
 68%|██████▊   | 77.0M/113M [00:03<00:01, 24.6MB/s]
 71%|███████   | 80.0M/113M [00:03<00:01, 23.1MB/s]
 75%|███████▌  | 85.0M/113M [00:03<00:01, 28.3MB/s]
 78%|███████▊  | 88.0M/113M [00:04<00:00, 28.6MB/s]
 81%|████████  | 91.0M/113M [00:04<00:00, 23.8MB/s]
 86%|████████▌ | 97.0M/113M [00:04<00:00, 32.2MB/s]
 89%|████████▉ | 101M/113M [00:04<00:00, 31.4MB/s]
 93%|█████████▎| 105M/113M [00:04<00:00, 33.0MB/s]
 97%|█████████▋| 109M/113M [00:04<00:00, 32.3MB/s]
100%|██████████| 113M/113M [00:04<00:00, 31.9MB/s]
100%|██████████| 113M/113M [00:04<00:00, 24.2MB/s]

In [4]:
# Carregando o dataset sem extração manual de arquivos

with zipfile.ZipFile(dataset_path, 'r') as dataset_ref:
    dataset_ref.printdir()

    for dataset_name in dataset_ref.namelist():
        if dataset_name.endswith('.csv'):
            print(f"Filename: {dataset_name}")            
            with dataset_ref.open(dataset_name) as dataset:
                df = pd.read_csv(dataset)

File Name                                             Modified             Size
universal_top_spotify_songs.csv                2024-11-29 15:01:32    346764771
Filename: universal_top_spotify_songs.csv

## 2 Explorando o dataset

* Descobrindo dados existentes;

In [5]:
df.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,5vNRhkKd0yEAg8suGBpjeY,APT.,"ROSÉ, Bruno Mars",1,0,1,NaN,2024-11-27,98,False,...,0,-4.477,0,0.2600,0.0283,0.0,0.3550,0.939,149.027,4
1,2plbrEY59IikOBgBGLjaoe,Die With A Smile,"Lady Gaga, Bruno Mars",2,0,-1,NaN,2024-11-27,100,False,...,6,-7.777,0,0.0304,0.3080,0.0,0.1220,0.535,157.969,3
2,2CGNAOSuO1MEFCbBRgUzjd,luther (with sza),"Kendrick Lamar, SZA",3,0,47,NaN,2024-11-27,64,False,...,2,-7.546,1,0.1250,0.2510,0.0,0.2480,0.576,138.008,4
3,0nj9Bq5sHDiTxSHunhgkFb,squabble up,Kendrick Lamar,4,0,46,NaN,2024-11-27,86,True,...,0,-5.568,1,0.1980,0.0206,0.0,0.0783,0.711,103.921,4
4,0aB0v4027ukVziUGwVGYpG,tv off (feat. lefty gunplay),"Kendrick Lamar, Lefty Gunplay",5,1,45,NaN,2024-11-27,85,True,...,6,-6.679,0,0.2630,0.0837,0.0,0.4230,0.548,100.036,4

In [6]:
dataset_columns = list(df.columns)
dataset_columns

['spotify_id',
 'name',
 'artists',
 'daily_rank',
 'daily_movement',
 'weekly_movement',
 'country',
 'snapshot_date',
 'popularity',
 'is_explicit',
 'duration_ms',
 'album_name',
 'album_release_date',
 'danceability',
 'energy',
 'key',
 'loudness',
 'mode',
 'speechiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'valence',
 'tempo',
 'time_signature']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1468130 entries, 0 to 1468129
Data columns (total 25 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   spotify_id          1468130 non-null  object
 1   name                1468101 non-null  object
 2   artists             1468102 non-null  object
 3   daily_rank          1468130 non-null  int64
 4   daily_movement      1468130 non-null  int64
 5   weekly_movement     1468130 non-null  int64
 6   country             1448123 non-null  object
 7   snapshot_date       1468130 non-null  object
 8   popularity          1468130 non-null  int64
 9   is_explicit         1468130 non-null  bool
 10  duration_ms         1468130 non-null  int64
 11  album_name          1467460 non-null  object
 12  album_release_date  1467623 non-null  object
 13  danceability        1468130 non-null  float64
 14  energy              1468130 non-null  float64
 15  key                 1468130 non-null  int64
 16  loudness            1468130 non-null  float64
 17  mode                1468130 non-null  int64
 18  speechiness         1468130 non-null  float64
 19  acousticness        1468130 non-null  float64
 20  instrumentalness    1468130 non-null  float64
 21  liveness            1468130 non-null  float64
 22  valence             1468130 non-null  float64
 23  tempo               1468130 non-null  float64
 24  time_signature      1468130 non-null  int64
dtypes: bool(1), float64(9), int64(8), object(7)
memory usage: 270.2+ MB

## 3 Descrevendo o dataset

* Criando dataset somente com os álbuns e país de interesse;
* Tratando coluna de data
* Criando novas colunas

In [10]:
# Selecionando albuns de interesse e país de interesse

us_dataset = df[(df['album_name'].isin(["COWBOY CARTER",
                                        "THE TORTURED POETS DEPARTMENT",
                                        "HIT ME HARD AND SOFT",
                                        "Short n' Sweet"])) &
            (df['country'] == 'US')].copy()

us_dataset.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
267,6dOtVTDdiauQNBQEDOtlAB,BIRDS OF A FEATHER,Billie Eilish,18,0,-13,US,2024-11-27,97,False,...,2,-10.171,1,0.0358,0.200,0.060800,0.117,0.438,104.978,4
272,5G2f63n7IPVPPjfNIGih7Q,Taste,Sabrina Carpenter,23,3,-17,US,2024-11-27,93,False,...,3,-4.086,1,0.0640,0.101,0.000000,0.297,0.721,112.964,4
276,3QaPy1KgI7nu9FJEQUgn6h,WILDFLOWER,Billie Eilish,27,2,-15,US,2024-11-27,93,False,...,6,-12.002,0,0.0431,0.612,0.000271,0.170,0.126,148.101,4
283,2HRqTpkrJO5ggZyyK6NPWz,Espresso,Sabrina Carpenter,34,-2,-18,US,2024-11-27,88,True,...,0,-5.282,1,0.0293,0.131,0.000005,0.205,0.708,103.963,4
288,2tHwzyyOLoWSFqYNjeVMzj,Please Please Please,Sabrina Carpenter,39,-2,-16,US,2024-11-27,87,True,...,9,-6.086,1,0.0531,0.257,0.000000,0.104,0.621,107.015,4

In [14]:
# Tratando coluna de data

us_dataset['snapshot_date'] = pd.to_datetime(us_dataset['snapshot_date'], errors='coerce')

In [22]:
print('Número de colunas: ', us_dataset.shape[1])
print('Número de registros: ', us_dataset.shape[0])

Número de colunas:  26
Número de registros:  1833

In [15]:
# Criando coluna de artista principal

us_dataset.loc[:, 'main_artist'] = us_dataset['artists'].apply(lambda x: x.split(',')[0])

In [16]:
us_dataset.head()

,spotify_id,name,artists,daily_rank,daily_movement,weekly_movement,country,snapshot_date,popularity,is_explicit,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,main_artist
267,6dOtVTDdiauQNBQEDOtlAB,BIRDS OF A FEATHER,Billie Eilish,18,0,-13,US,2024-11-27,97,False,...,-10.171,1,0.0358,0.200,0.060800,0.117,0.438,104.978,4,Billie Eilish
272,5G2f63n7IPVPPjfNIGih7Q,Taste,Sabrina Carpenter,23,3,-17,US,2024-11-27,93,False,...,-4.086,1,0.0640,0.101,0.000000,0.297,0.721,112.964,4,Sabrina Carpenter
276,3QaPy1KgI7nu9FJEQUgn6h,WILDFLOWER,Billie Eilish,27,2,-15,US,2024-11-27,93,False,...,-12.002,0,0.0431,0.612,0.000271,0.170,0.126,148.101,4,Billie Eilish
283,2HRqTpkrJO5ggZyyK6NPWz,Espresso,Sabrina Carpenter,34,-2,-18,US,2024-11-27,88,True,...,-5.282,1,0.0293,0.131,0.000005,0.205,0.708,103.963,4,Sabrina Carpenter
288,2tHwzyyOLoWSFqYNjeVMzj,Please Please Please,Sabrina Carpenter,39,-2,-16,US,2024-11-27,87,True,...,-6.086,1,0.0531,0.257,0.000000,0.104,0.621,107.015,4,Sabrina Carpenter

In [ ]:
# Listando artistas principais

main_artists = sorted(list(set(us_dataset['main_artist'])))
main_artists

['Beyoncé', 'Billie Eilish', 'Sabrina Carpenter', 'Taylor Swift']

In [ ]:
# Número de aparições no Top 50

print('Número de aparições na playlist Top 50 dos EUA')
for artist in main_artists:
    x = us_dataset[us_dataset['main_artist'] == artist].shape[0]
    print(f'{artist}: {x}')
print(f'Data de referencia: ({us_dataset['snapshot_date'].max()})')

Número de aparições na playlist Top 50 dos EUA
Beyoncé: 136
Billie Eilish: 593
Sabrina Carpenter: 567
Taylor Swift: 537
Data de referencia: (2024-11-27 00:00:00)

In [55]:
# Data de lançamento

release_date = us_dataset[['album_name', 'main_artist', 'album_release_date']].drop_duplicates()
release_date

                           album_name        main_artist album_release_date
267              HIT ME HARD AND SOFT      Billie Eilish         2024-05-17
272                    Short n' Sweet  Sabrina Carpenter         2024-08-23
347375  THE TORTURED POETS DEPARTMENT       Taylor Swift         2024-04-18
800465                  COWBOY CARTER            Beyoncé         2024-03-29
826021                  COWBOY CARTER            Beyoncé         2024-03-27

In [56]:
# Removendo álbum duplicado

release_date.drop(index=release_date.index[-1], inplace=True)
release_date

                           album_name        main_artist album_release_date
267              HIT ME HARD AND SOFT      Billie Eilish         2024-05-17
272                    Short n' Sweet  Sabrina Carpenter         2024-08-23
347375  THE TORTURED POETS DEPARTMENT       Taylor Swift         2024-04-18
800465                  COWBOY CARTER            Beyoncé         2024-03-29

In [ ]:
# Criando range da semana

release_date['date_range'] = release_date['album_release_date'].apply(lambda date: pd.date_range(start=date, periods=7))
release_date

,album_name,main_artist,album_release_date,date_range
267,HIT ME HARD AND SOFT,Billie Eilish,2024-05-17,"DatetimeIndex(['2024-05-17', '2024-05-18', '20..."
272,Short n' Sweet,Sabrina Carpenter,2024-08-23,"DatetimeIndex(['2024-08-23', '2024-08-24', '20..."
347375,THE TORTURED POETS DEPARTMENT,Taylor Swift,2024-04-18,"DatetimeIndex(['2024-04-18', '2024-04-19', '20..."
800465,COWBOY CARTER,Beyoncé,2024-03-29,"DatetimeIndex(['2024-03-29', '2024-03-30', '20..."

In [ ]:
# Definindo função de gerar dataframe da primeira semana

def first_week_filter(artist):
    date_range = release_date.loc[release_date['main_artist'] == artist, 'date_range'].iloc[0]

    # Filtrar o DataFrame
    first_week_df = us_dataset[
        (us_dataset['main_artist'] == artist) & 
        (us_dataset['snapshot_date'].isin(date_range))
    ]

    return first_week_df

In [86]:
print('Número de aparições na playlist Top50 na primeira semana de lançamento')

for artist in main_artists:
    artist_first_week_df = first_week_filter(artist)
    print(f'{artist}: {artist_first_week_df.shape[0]}')

Número de aparições na playlist Top50 na primeira semana de lançamento
Beyoncé: 100
Billie Eilish: 60
Sabrina Carpenter: 60
Taylor Swift: 16